title : Uncertainty is a principle!
description: Hello! I'm Taniya, I study Statistics at university. I love to listen piano.
python : I use most of the times for ML and NN works
R: For Statistical analysis of data
theme: jekyll-theme-dinky
logo : docs/assets/dice.png
