title : Uncertainty is a principle
description: I study Statistics at university. I love to listen piano.
logo : https://github.com/PolleyTaniya/Lnut.github.io/blob/main/docs/assets/IMG20241226073054.jpg
